Feature/signIn Code  Review
coditas-eltp-golang-learners-2024/Stock_broker_application_prahlad pull request #2
Opened 2024-04-10 12:21 UTC by PrahladSingh-coditas

### This pull request completes the feature/signIn functionality by implementing dependency injection for better code modularity and testability.

**Changes Made:**
- Implemented dependency injection in the signIn feature to decouple components and promote easier unit testing.
- Done with few minor changes as suggested by mentors.

<img width="1440" alt="Screenshot 2024-04-10 at 5 47 57 PM" src="https://github.com/coditas-eltp-golang-learners-2024/Stock_broker_application_prahlad/assets/158143460/d10b72ac-3258-42f9-b83e-dff31a84cb15">

2024-04-10 19:05 UTC, vipin-raj-coditas requested changes

2024-04-10 19:05 UTC, vipin-raj-coditas commented on src/app/authentication/constants/constants.go
> +var UserInstance = models.UserInfo{}
Don't define UserInstance here.

2024-04-10 19:05 UTC, vipin-raj-coditas commented on src/app/authentication/handlers/signUpHandler.go
> +	c.JSON(http.StatusOK, gin.H{"message": "User information inserted successfully"})
Store all error messages in error.go and all constants in constants.go

2024-04-10 19:05 UTC, vipin-raj-coditas commented on src/app/authentication/models/signInModel.go
> +	Password string `json:"password" validate:"required"`
Add all possible validation for password

2024-04-10 19:05 UTC, vipin-raj-coditas commented on src/app/authentication/models/signUpModel.go
>  	Password      string `json:"user_password"`
Keep all json name as camelCase as best practice and also add all possible in built and custom Validation.
Refer https://pkg.go.dev/github.com/go-playground/validator/v10#section-readme

2024-04-10 19:05 UTC, vipin-raj-coditas commented on src/app/authentication/resources/application.yml
> +  Username: root
Keep Username as small case.

2024-04-12 04:44 UTC, Gauravi-S commented on constants/error.go
> +	// ErrUserExistenceFailed indicates a failure in checking user existence.
No need to add comments for every line, if the understanding of code line is obvious.

2024-04-12 05:39 UTC, Gauravi-S commented on constants/routes.go
> +)
```suggestion
// User related routes (keep the comment here)
const (
	CreateUserRoute = "/signup"
	SignInRoute     = "/signin"
)
```

2024-04-12 05:40 UTC, Gauravi-S commented on repo/signUpRepo.go
> +func (r *UserRepository) CheckIfUserExistsByEmail(email string) (bool, error) {
rename r to appropriate variable name.

2024-04-12 05:59 UTC, Gauravi-S commented on handlers/signUpHandler.go
> +}
Move both the models SuccessResponses and ErrorResponses in new file genericModels.go in models folder.
same for these models in signInHandler.go

2024-04-12 06:00 UTC, Gauravi-S commented on models/signUpModel.go
> +}
Move this model in new file dbModels.go in models folder.

2024-04-12 06:03 UTC, Gauravi-S commented on repo/signInRepo.go
> +// @Router /verify [post]
no need to  add swagger syntax documentation for all the functions, just add one liner description if needed.

2024-04-12 06:03 UTC, Gauravi-S commented on router/router.go
> +	// @Router /users [post]
remove the documentation.

2024-04-12 06:04 UTC, Gauravi-S commented on router/router.go
> +	router.POST(constants.CreateUserRoute, handlers.PostUsersData)
keep all the router.POST together in code block like

router.POST(constants.CreateUserRoute, handlers.PostUsersData)
router.POST(constants.SignInRoute, handlers.SignInHandler(signInService))

2024-04-15 10:05 UTC, closed without merging